### ISSUE TITLE
Advice on data analysis

### ISSUE THREAD

**Issue by apelin20** [PathwayAndDataAnalysis/causalpath#9]
Hello,

I have phosphoprotein fold change data between 2 conditions: virus and no virus. I have extracted the phospho sites that are significant and have a log2 FC value >= 1 || <= -1. I do not know the effect of any proteins so I want to use online available databases. Because I need to specify a threshold in the parameter file, I am showing absolute values of fold changes so as to preserve the negative ones. head input file:
```
ID      Symbols  Sites                     Effect  VACV-MOCK
ABCC1   ABCC1    S915|S918|T931                    0.201634
ABCC3   ABCC3    S908|S911                         1.55639
ABCC4   ABCC4    S665                              1.32193
ABCF1   ABCF1    S22|S24                           1.19535
ABLIM1  ABLIM1   S215|S216                         1.11103
ABLIM2  ABLIM2   S364                              5.05889
ACAP2   ACAP2    S379|S384|S387                    1.17632
ACBD5   ACBD5    S418                              1.64155
ACIN1   ACIN1    S208|S216|S240|S243|S388          1.38405
```
My parameters.txt file is as follows:

```
proteomics-values-file = PH_sig-FDR-0.05_Sites_AvrFC_CausalPath.table
id-column = ID
symbols-column = Symbols
sites-column = Sites
effect-column = Effect
value-transformation = geometric-mean
value-column = VACV-MOCK
threshold-for-data-significance = 1 phosphoprotein
threshold-for-data-significance	= 1 protein
calculate-network-significance = true
permutations-for-significance = 10000
fdr-threshold-for-network-significance = 0.1
use-network-significance-for-causal-reasoning = true
color-saturation-value = 10
show-all-genes-with-proteomic-data = true
```

Am I doing this correctly? I also tried
`built-in-network-resource-selection = PC REACH PhosphoNetworks IPTMNet RHOGEF PCTCGAConsensus TRRUST TFactS NetworKIN`
but get:
`Exception in thread "main" java.lang.RuntimeException: Network resource not recognized: PC REACH PhosphoNetworks IPTMNet RHOGEF PCTCGAConsensus TRRUST TFactS NetworKIN`
or built-in-network-resource-selection = PhosphoNetworks gives:
```
Exception in thread "main" java.lang.NullPointerException
	at org.panda.causalpath.resource.NetworkLoader.cleanUpConflicts(NetworkLoader.java:292)
	at org.panda.causalpath.resource.NetworkLoader.cleanUpConflicts(NetworkLoader.java:254)
	at org.panda.causalpath.resource.NetworkLoader.load(NetworkLoader.java:121)
	at org.panda.causalpath.run.CausalPath.run(CausalPath.java:419)
	at org.panda.causalpath.run.CausalPath.main(CausalPath.java:303)
```

Am I doing this right? Thank you for your help.

**Comment by ozgunbabur** [comment]
Hi apelin20,

You shouldn't use the absolute values of log2 FC value. You need to include their signs otherwise the logical reasoning in the CausalPath algorithm will not work. Don't worry about the threshold being a positive number. It works symmetrically on the negative part. When you use 1 as a threshold, values larger than 1 and smaller than -1 are considered significant.

Here are some comments on your parameters file:

```threshold-for-data-significance = 1 protein```

If you only have phosphoproteomic measurements, you don't need a threshold for global protein levels. You can remove this line.

```calculate-network-significance = true```

When you turn on network significance calculations, please also make sure that you provide all the data in the data file, including all the insignificant rows. I am saying this because you wrote "I have extracted the phospho sites that are significant ...". If you only have the significant rows in your data, the network significance calculations will not work correctly.

```built-in-network-resource-selection = PC REACH PhosphoNetworks IPTMNet RHOGEF PCTCGAConsensus TRRUST TFactS NetworKIN```

You don't need this line unless you want to experiment with different network resources. When you omit it, CausalPath will use PC, PhosphoSitePlus, PhosphoNetworks, IPTMNet, TRRUST and TFactS by default. Those are the high-quality tier. Other options are experimental.

Also, the correct notation for this parameter is to repeat it for each resource, like:
```
built-in-network-resource-selection = PC 
built-in-network-resource-selection = REACH 
built-in-network-resource-selection = PhosphoNetworks
```

Let me know if you have more questions.

**Comment by apelin20** [comment]
Thank you, that was super helpful, the data is starting to make more sense. I have some follow up questions.

I am now supplying fold changes for all data/genes to be able to use "calculate-network-significance". How do I also specify per-calculated FDR values so as to be able to focus on significant phosphoproteins.

My data is phosphoprotein only, where in the parameters file is that specified?

I also have a concern with the way I formatted my input data for CausalPath. For most phosphoproteins I have fold-change values for multiple phospho sites, and what I do now is just average them fold-change values per protein, does that make sense? Or should I just provide the highest/lowest FC value?

Thanks again for all your help!

**Comment by ozgunbabur** [comment]
When you have FDR values (or adjusted p-values) for each data row, one way you can use them in CausalPath is to convert them into **signed p-values**. A signed p-value is a p-value with a positive or a negative sign indicating the direction of change. For instance, -0.01 indicates a downregulation with p=0.01, while 0.2 indicates an upregulation with p=0.2. You can derive those signs using the fold change values.

To use signed p-values you need to have
```
value-transformation = signed-p-values
```
in your parameters file. You need to specify the column that contains the signed p-value by
```
value-column = SignedP
```
assuming the name of that column is SignedP in your reformatted data file.

When your data has only phosphoproteins, you don't need to set data significance thresholds for other data types. You only need
```
threshold-for-data-significance = 0.1 phosphoprotein
``` 
Note that this is not the "fdr-threshold-for-data-significance" since your p-values already indicate an FDR cutoff.
